[workspace]
resolver = "3"
members = ["day*"]


[workspace.package]
version = "0.1.0"
edition = "2024"


[workspace.dependencies]
aoc-utils.path = "../aoc-utils/aoc-utils"

rstest = "0.26.1"

winnow = "0.7.14"

good_lp = { version = "1.14.2", features = [
    "microlp",
], default-features = false }
