[workspace]
resolver = "2"

members = ["day-*"]


[workspace.dependencies]
aoc-utils = { path = "../aoc-utils/aoc-utils" }
aoc-macros = { path = "../aoc-utils/aoc-macros" }

rstest = "0.24.0"

regex = "1.11.1"
winnow = "0.6.20"

itertools = "0.14.0"
num = "0.4.3"
image = "0.25.5"
