[package]
name = "aoc-macros"
version = "0.1.0"
edition = "2021"


[lib]
proc-macro = true


[dependencies]
aoc-utils = { path = "../aoc-utils" }
quote = { workspace = true }
syn = { workspace = true }
