[package]
name = "day-13"
version = "0.1.0"
edition = "2021"


[features]
test-answers = []


[dependencies]
aoc-macros = { workspace = true }
winnow = { workspace = true }


[dev-dependencies]
aoc-utils = { workspace = true }
rstest = { workspace = true }
